#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 19 01:12:00 2025

@author: hussein.sharadga
"""

import gurobipy as gp
from gurobipy import GRB



# This is based on


# intialize the model
m=gp.Model()

# m.Params.Presolve=0
# Add variables
x=m.addVar(vtype=GRB.BINARY)
y=m.addVar(vtype=GRB.BINARY)
z=m.addVar(vtype=GRB.BINARY)



# This is a relaxation of z=max(x,y) when x,y,and z are binary.

# Add constraints

m.addConstr(z>=x)
m.addConstr(z>=y)
m.addConstr(z<=x+y)

m.addConstr(x==0)
# m.addConstr(y==0)



# set objective function (z)  or (obj) 
obj=(x+y+z)
m.setObjective(-obj)



# run the model
m.optimize()

# Check optimization status
if m.status == GRB.OPTIMAL:
    print('Optimal solution found')
    # Print variable values
    for var in m.getVars():
        print(f'{var.varName}: {var.x}')
    # Print objective value
    print(f'Objective: {m.objVal}')
else:
    print('No solution found')

